### ISSUE TITLE
Add Intra-request parallelization

### ISSUE THREAD

**Issue by PropzSaladaz** [skalenetwork/sgxwallet#471]
### Description

- Each `getDecryptionShares` request should execute share decryption in parallel to improve speedup

**Comment by andriy66** [comment]
Verified on:
**Skaled:** skalenetwork/schain:consensus-895-debug-logs-relwithdebinfo
**Schain:** mirage-qa-hoodi-1

Note: **The performance has not increased with separate SGX**

**Docker compose file:**
```
version: '3'
services:
  sgxwallet:
    image: skalenetwork/sgxwallet:1.10.0-develop.6
    restart: unless-stopped
    ports:
      - "1026:1026"
      - "1027:1027"
      - "1028:1028"
      - "1029:1029"
      - "1030:1030"
      - "1031:1031"
    devices:
      - "/dev/isgx"
      - "/dev/sg1"
    volumes:
      - ./sgx_data:/usr/src/sdk/sgx_data
      -  /dev/urandom:/dev/random
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "4"
    command: -s -y -d -e -b -t8
    healthcheck:
      test: ["CMD", "ls", "/dev/isgx", "/dev/sg1"]
```

<img width="2112" height="1001" alt="Image" src="https://github.com/user-attachments/assets/9b734bdc-c6da-41ee-baac-0fc097df832a" />

<img width="2112" height="1001" alt="Image" src="https://github.com/user-attachments/assets/e4401904-5e5a-423f-802e-7ac4c6969ba7" />

<img width="2112" height="890" alt="Image" src="https://github.com/user-attachments/assets/083d022d-53b5-47a5-bd5b-0ff89dfa2ad2" />
